In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('E:\covid-data-analysis\data/owid-covid-data.csv')

In [4]:
df

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-01-05,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-01-06,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-01-07,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-01-08,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-01-09,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
429430,ZWE,Africa,Zimbabwe,2024-07-31,266386.0,0.0,0.0,5740.0,0.0,0.0,...,30.7,36.79,1.7,61.49,0.57,16320539,NaN,NaN,NaN,NaN
429431,ZWE,Africa,Zimbabwe,2024-08-01,266386.0,0.0,0.0,5740.0,0.0,0.0,...,30.7,36.79,1.7,61.49,0.57,16320539,NaN,NaN,NaN,NaN
429432,ZWE,Africa,Zimbabwe,2024-08-02,266386.0,0.0,0.0,5740.0,0.0,0.0,...,30.7,36.79,1.7,61.49,0.57,16320539,NaN,NaN,NaN,NaN
429433,ZWE,Africa,Zimbabwe,2024-08-03,266386.0,0.0,0.0,5740.0,0.0,0.0,...,30.7,36.79,1.7,61.49,0.57,16320539,NaN,NaN,NaN,NaN
429434,ZWE,Africa,Zimbabwe,2024-08-04,266386.0,0.0,0.0,5740.0,0.0,0.0,...,30.7,36.79,1.7,61.49,0.57,16320539,NaN,NaN,NaN,NaN

In [5]:
df.shape

(429435, 67)

In [6]:
df.info

<bound method DataFrame.info of        iso_code continent     location        date  total_cases  new_cases  \
0           AFG      Asia  Afghanistan  2020-01-05          0.0        0.0
1           AFG      Asia  Afghanistan  2020-01-06          0.0        0.0
2           AFG      Asia  Afghanistan  2020-01-07          0.0        0.0
3           AFG      Asia  Afghanistan  2020-01-08          0.0        0.0
4           AFG      Asia  Afghanistan  2020-01-09          0.0        0.0
...         ...       ...          ...         ...          ...        ...
429430      ZWE    Africa     Zimbabwe  2024-07-31     266386.0        0.0
429431      ZWE    Africa     Zimbabwe  2024-08-01     266386.0        0.0
429432      ZWE    Africa     Zimbabwe  2024-08-02     266386.0        0.0
429433      ZWE    Africa     Zimbabwe  2024-08-03     266386.0        0.0
429434      ZWE    Africa     Zimbabwe  2024-08-04     266386.0        0.0

        new_cases_smoothed  total_deaths  new_deaths  new_deaths_smoothed  \
0                      NaN           0.0         0.0                  NaN
1                      NaN           0.0         0.0                  NaN
2                      NaN           0.0         0.0                  NaN
3                      NaN           0.0         0.0                  NaN
4                      NaN           0.0         0.0                  NaN
...                    ...           ...         ...                  ...
429430                 0.0        5740.0         0.0                  0.0
429431                 0.0        5740.0         0.0                  0.0
429432                 0.0        5740.0         0.0                  0.0
429433                 0.0        5740.0         0.0                  0.0
429434                 0.0        5740.0         0.0                  0.0

        ...  male_smokers  handwashing_facilities  hospital_beds_per_thousand  \
0       ...           NaN                   37.75                         0.5
1       ...           NaN                   37.75                         0.5
2       ...           NaN                   37.75                         0.5
3       ...           NaN                   37.75                         0.5
4       ...           NaN                   37.75                         0.5
...     ...           ...                     ...                         ...
429430  ...          30.7                   36.79                         1.7
429431  ...          30.7                   36.79                         1.7
429432  ...          30.7                   36.79                         1.7
429433  ...          30.7                   36.79                         1.7
429434  ...          30.7                   36.79                         1.7

        life_expectancy  human_development_index  population  \
0                 64.83                     0.51    41128772
1                 64.83                     0.51    41128772
2                 64.83                     0.51    41128772
3                 64.83                     0.51    41128772
4                 64.83                     0.51    41128772
...                 ...                      ...         ...
429430            61.49                     0.57    16320539
429431            61.49                     0.57    16320539
429432            61.49                     0.57    16320539
429433            61.49                     0.57    16320539
429434            61.49                     0.57    16320539

        excess_mortality_cumulative_absolute  excess_mortality_cumulative  \
0                                        NaN                          NaN
1                                        NaN                          NaN
2                                        NaN                          NaN
3                                        NaN                          NaN
4                                        NaN                          NaN
...                                      ...                          ...
429430                                   NaN                          NaN
429431                                   NaN                          NaN
429432                                   NaN                          NaN
429433                                   NaN                          NaN
429434                                   NaN                          NaN

        excess_mortality  excess_mortality_cumulative_per_million
0                    NaN                                      NaN
1                    NaN                                      NaN
2                    NaN                                      NaN
3                    NaN                                      NaN
4                    NaN                                      NaN
...                  ...                                      ...
429430               NaN                                      NaN
429431               NaN                                      NaN
429432               NaN                                      NaN
429433               NaN                                      NaN
429434               NaN                                      NaN

[429435 rows x 67 columns]>

In [7]:
df.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-01-05,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-01-06,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-01-07,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-01-08,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-01-09,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN

In [8]:
print(df.shape)

(429435, 67)

In [9]:
print(df.head(10))

  iso_code continent     location        date  total_cases  new_cases  \
0      AFG      Asia  Afghanistan  2020-01-05          0.0        0.0
1      AFG      Asia  Afghanistan  2020-01-06          0.0        0.0
2      AFG      Asia  Afghanistan  2020-01-07          0.0        0.0
3      AFG      Asia  Afghanistan  2020-01-08          0.0        0.0
4      AFG      Asia  Afghanistan  2020-01-09          0.0        0.0
5      AFG      Asia  Afghanistan  2020-01-10          0.0        0.0
6      AFG      Asia  Afghanistan  2020-01-11          0.0        0.0
7      AFG      Asia  Afghanistan  2020-01-12          0.0        0.0
8      AFG      Asia  Afghanistan  2020-01-13          0.0        0.0
9      AFG      Asia  Afghanistan  2020-01-14          0.0        0.0

   new_cases_smoothed  total_deaths  new_deaths  new_deaths_smoothed  ...  \
0                 NaN           0.0         0.0                  NaN  ...
1                 NaN           0.0         0.0                  NaN  ...
2                 NaN           0.0         0.0                  NaN  ...
3                 NaN           0.0         0.0                  NaN  ...
4                 NaN           0.0         0.0                  NaN  ...
5                 0.0           0.0         0.0                  0.0  ...
6                 0.0           0.0         0.0                  0.0  ...
7                 0.0           0.0         0.0                  0.0  ...
8                 0.0           0.0         0.0                  0.0  ...
9                 0.0           0.0         0.0                  0.0  ...

   male_smokers  handwashing_facilities  hospital_beds_per_thousand  \
0           NaN                   37.75                         0.5
1           NaN                   37.75                         0.5
2           NaN                   37.75                         0.5
3           NaN                   37.75                         0.5
4           NaN                   37.75                         0.5
5           NaN                   37.75                         0.5
6           NaN                   37.75                         0.5
7           NaN                   37.75                         0.5
8           NaN                   37.75                         0.5
9           NaN                   37.75                         0.5

   life_expectancy  human_development_index  population  \
0            64.83                     0.51    41128772
1            64.83                     0.51    41128772
2            64.83                     0.51    41128772
3            64.83                     0.51    41128772
4            64.83                     0.51    41128772
5            64.83                     0.51    41128772
6            64.83                     0.51    41128772
7            64.83                     0.51    41128772
8            64.83                     0.51    41128772
9            64.83                     0.51    41128772

   excess_mortality_cumulative_absolute  excess_mortality_cumulative  \
0                                   NaN                          NaN
1                                   NaN                          NaN
2                                   NaN                          NaN
3                                   NaN                          NaN
4                                   NaN                          NaN
5                                   NaN                          NaN
6                                   NaN                          NaN
7                                   NaN                          NaN
8                                   NaN                          NaN
9                                   NaN                          NaN

   excess_mortality  excess_mortality_cumulative_per_million
0               NaN                                      NaN
1               NaN                                      NaN
2               NaN                                      NaN
3               NaN                                      NaN
4               NaN                                      NaN
5               NaN                                      NaN
6               NaN                                      NaN
7               NaN                                      NaN
8               NaN                                      NaN
9               NaN                                      NaN

[10 rows x 67 columns]

In [10]:
india_df =df[df['location'] =='India']

In [11]:
india_df.shape

(1682, 67)

In [12]:
india_df.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
173549,IND,Asia,India,2020-01-05,0.0,0.0,NaN,0.0,0.0,NaN,...,20.6,59.55,0.53,69.66,0.64,1417173120,NaN,NaN,NaN,NaN
173550,IND,Asia,India,2020-01-06,0.0,0.0,NaN,0.0,0.0,NaN,...,20.6,59.55,0.53,69.66,0.64,1417173120,NaN,NaN,NaN,NaN
173551,IND,Asia,India,2020-01-07,0.0,0.0,NaN,0.0,0.0,NaN,...,20.6,59.55,0.53,69.66,0.64,1417173120,NaN,NaN,NaN,NaN
173552,IND,Asia,India,2020-01-08,0.0,0.0,NaN,0.0,0.0,NaN,...,20.6,59.55,0.53,69.66,0.64,1417173120,NaN,NaN,NaN,NaN
173553,IND,Asia,India,2020-01-09,0.0,0.0,NaN,0.0,0.0,NaN,...,20.6,59.55,0.53,69.66,0.64,1417173120,NaN,NaN,NaN,NaN

In [13]:
pd.set_option('display.max_columns',None)

In [14]:
india_df.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths_per_million,new_deaths_per_million,new_deaths_smoothed_per_million,reproduction_rate,icu_patients,icu_patients_per_million,hosp_patients,hosp_patients_per_million,weekly_icu_admissions,weekly_icu_admissions_per_million,weekly_hosp_admissions,weekly_hosp_admissions_per_million,total_tests,new_tests,total_tests_per_thousand,new_tests_per_thousand,new_tests_smoothed,new_tests_smoothed_per_thousand,positive_rate,tests_per_case,tests_units,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters,new_vaccinations,new_vaccinations_smoothed,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,total_boosters_per_hundred,new_vaccinations_smoothed_per_million,new_people_vaccinated_smoothed,new_people_vaccinated_smoothed_per_hundred,stringency_index,population_density,median_age,aged_65_older,aged_70_older,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
173549,IND,Asia,India,2020-01-05,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,450.42,28.2,5.99,3.41,6426.67,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64,1417173120,NaN,NaN,NaN,NaN
173550,IND,Asia,India,2020-01-06,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,450.42,28.2,5.99,3.41,6426.67,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64,1417173120,NaN,NaN,NaN,NaN
173551,IND,Asia,India,2020-01-07,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,450.42,28.2,5.99,3.41,6426.67,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64,1417173120,NaN,NaN,NaN,NaN
173552,IND,Asia,India,2020-01-08,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,450.42,28.2,5.99,3.41,6426.67,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64,1417173120,NaN,NaN,NaN,NaN
173553,IND,Asia,India,2020-01-09,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,450.42,28.2,5.99,3.41,6426.67,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64,1417173120,NaN,NaN,NaN,NaN

In [16]:
india_df = df[df['location'] == 'India'].copy()

In [17]:
india_df['date'] = pd.to_datetime(india_df['date'])

In [18]:
india_df

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths_per_million,new_deaths_per_million,new_deaths_smoothed_per_million,reproduction_rate,icu_patients,icu_patients_per_million,hosp_patients,hosp_patients_per_million,weekly_icu_admissions,weekly_icu_admissions_per_million,weekly_hosp_admissions,weekly_hosp_admissions_per_million,total_tests,new_tests,total_tests_per_thousand,new_tests_per_thousand,new_tests_smoothed,new_tests_smoothed_per_thousand,positive_rate,tests_per_case,tests_units,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters,new_vaccinations,new_vaccinations_smoothed,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,total_boosters_per_hundred,new_vaccinations_smoothed_per_million,new_people_vaccinated_smoothed,new_people_vaccinated_smoothed_per_hundred,stringency_index,population_density,median_age,aged_65_older,aged_70_older,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
173549,IND,Asia,India,2020-01-05,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,450.42,28.2,5.99,3.41,6426.67,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64,1417173120,NaN,NaN,NaN,NaN
173550,IND,Asia,India,2020-01-06,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,450.42,28.2,5.99,3.41,6426.67,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64,1417173120,NaN,NaN,NaN,NaN
173551,IND,Asia,India,2020-01-07,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,450.42,28.2,5.99,3.41,6426.67,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64,1417173120,NaN,NaN,NaN,NaN
173552,IND,Asia,India,2020-01-08,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,450.42,28.2,5.99,3.41,6426.67,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64,1417173120,NaN,NaN,NaN,NaN
173553,IND,Asia,India,2020-01-09,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,450.42,28.2,5.99,3.41,6426.67,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64,1417173120,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175226,IND,Asia,India,2024-08-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.206868e+09,1.027439e+09,951990535.0,227438516.0,10.0,9.0,155.72,72.5,67.18,16.05,0.0,3.0,0.0,NaN,450.42,28.2,5.99,3.41,6426.67,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64,1417173120,NaN,NaN,NaN,NaN
175227,IND,Asia,India,2024-08-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.206868e+09,1.027439e+09,951990537.0,227438519.0,6.0,8.0,155.72,72.5,67.18,16.05,0.0,3.0,0.0,NaN,450.42,28.2,5.99,3.41,6426.67,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64,1417173120,NaN,NaN,NaN,NaN
175228,IND,Asia,India,2024-08-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.206868e+09,1.027439e+09,951990545.0,227438523.0,16.0,9.0,155.72,72.5,67.18,16.05,0.0,3.0,0.0,NaN,450.42,28.2,5.99,3.41,6426.67,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64,1417173120,NaN,NaN,NaN,NaN
175229,IND,Asia,India,2024-08-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.206868e+09,1.027439e+09,951990547.0,227438524.0,7.0,8.0,155.72,72.5,67.18,16.05,0.0,3.0,0.0,NaN,450.42,28.2,5.99,3.41,6426.67,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64,1417173120,NaN,NaN,NaN,NaN
175230,IND,Asia,India,2024-08-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.206868e+09,1.027439e+09,951990552.0,NaN,7.0,8.0,155.72,72.5,67.18,NaN,0.0,3.0,0.0,NaN,450.42,28.2,5.99,3.41,6426.67,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.64,1417173120,NaN,NaN,NaN,NaN

In [19]:
india_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1682 entries, 173549 to 175230
Data columns (total 67 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   iso_code                                    1682 non-null   object
 1   continent                                   1682 non-null   object
 2   location                                    1682 non-null   object
 3   date                                        1682 non-null   datetime64[ns]
 4   total_cases                                 1674 non-null   float64
 5   new_cases                                   1674 non-null   float64
 6   new_cases_smoothed                          1669 non-null   float64
 7   total_deaths                                1674 non-null   float64
 8   new_deaths                                  1674 non-null   float64
 9   new_deaths_smoothed                         1669 non-null   float64
 10  total_cases_per_million                     1674 non-null   float64
 11  new_cases_per_million                       1674 non-null   float64
 12  new_cases_smoothed_per_million              1669 non-null   float64
 13  total_deaths_per_million                    1674 non-null   float64
 14  new_deaths_per_million                      1674 non-null   float64
 15  new_deaths_smoothed_per_million             1669 non-null   float64
 16  reproduction_rate                           1024 non-null   float64
 17  icu_patients                                0 non-null      float64
 18  icu_patients_per_million                    0 non-null      float64
 19  hosp_patients                               0 non-null      float64
 20  hosp_patients_per_million                   0 non-null      float64
 21  weekly_icu_admissions                       0 non-null      float64
 22  weekly_icu_admissions_per_million           0 non-null      float64
 23  weekly_hosp_admissions                      0 non-null      float64
 24  weekly_hosp_admissions_per_million          0 non-null      float64
 25  total_tests                                 810 non-null    float64
 26  new_tests                                   795 non-null    float64
 27  total_tests_per_thousand                    810 non-null    float64
 28  new_tests_per_thousand                      795 non-null    float64
 29  new_tests_smoothed                          824 non-null    float64
 30  new_tests_smoothed_per_thousand             824 non-null    float64
 31  positive_rate                               816 non-null    float64
 32  tests_per_case                              816 non-null    float64
 33  tests_units                                 831 non-null    object
 34  total_vaccinations                          1250 non-null   float64
 35  people_vaccinated                           1245 non-null   float64
 36  people_fully_vaccinated                     1209 non-null   float64
 37  total_boosters                              887 non-null    float64
 38  new_vaccinations                            1220 non-null   float64
 39  new_vaccinations_smoothed                   1305 non-null   float64
 40  total_vaccinations_per_hundred              1250 non-null   float64
 41  people_vaccinated_per_hundred               1245 non-null   float64
 42  people_fully_vaccinated_per_hundred         1209 non-null   float64
 43  total_boosters_per_hundred                  887 non-null    float64
 44  new_vaccinations_smoothed_per_million       1305 non-null   float64
 45  new_people_vaccinated_smoothed              1305 non-null   float64
 46  new_people_vaccinated_smoothed_per_hundred  1305 non-null   float64
 47  stringency_index                            1092 non-null   float64
 48  population_density                          1682 non-null   float64
 49  median_age                                  1682 non-null   float64
 50  aged_65_older                               1682 non-null   float64
 51  aged_70_older                               1682 non-null   float64
 52  gdp_per_capita                              1682 non-null   float64
 53  extreme_poverty                             1682 non-null   float64
 54  cardiovasc_death_rate                       1682 non-null   float64
 55  diabetes_prevalence                         1682 non-null   float64
 56  female_smokers                              1682 non-null   float64
 57  male_smokers                                1682 non-null   float64
 58  handwashing_facilities                      1682 non-null   float64
 59  hospital_beds_per_thousand                  1682 non-null   float64
 60  life_expectancy                             1682 non-null   float64
 61  human_development_index                     1682 non-null   float64
 62  population                                  1682 non-null   int64
 63  excess_mortality_cumulative_absolute        0 non-null      float64
 64  excess_mortality_cumulative                 0 non-null      float64
 65  excess_mortality                            0 non-null      float64
 66  excess_mortality_cumulative_per_million     0 non-null      float64
dtypes: datetime64[ns](1), float64(61), int64(1), object(4)
memory usage: 893.6+ KB